/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BL.BL_Aro;
import BL.BL_Cliente;
import BL.BL_Llanta;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author michael
 */
public final class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private BL_Cliente cliente;
    private BL_Llanta llanta;
    private BL_Aro aro;
    private int filaSeleccionada;
    private ArrayList<BL_Cliente> listaClientes;
    private ArrayList<BL_Llanta> listaLlantas;
    private ArrayList<BL_Aro> listaAros;
    private DefaultTableModel dtmClientes;
    private DefaultTableModel dtmLlantas;
    private DefaultTableModel dtmAros;
    private TableRowSorter trsfiltroCliente;
    private TableRowSorter trsfiltroLlantas;
    private TableRowSorter trsfiltroAros;
    int resaltado;

    public Principal() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../IMG/tire-icon.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
        cargarClientes();
        cargarLlantas();
        cargarAros();
        jt_clientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jt_llantas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jt_aros.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        resaltado=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pum_tb = new javax.swing.JPopupMenu();
        jmi_ver = new javax.swing.JMenuItem();
        jmi_modificar = new javax.swing.JMenuItem();
        jmi_eliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        panel_tabs = new javax.swing.JTabbedPane();
        jp_clientes = new javax.swing.JPanel();
        jl_Buscar = new javax.swing.JLabel();
        tf_buscarCliente = new javax.swing.JTextField();
        bt_ver = new javax.swing.JButton();
        bt_agregar = new javax.swing.JButton();
        bt_modificar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_clientes = new javax.swing.JTable();
        jp_llantas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_llantas = new javax.swing.JTable();
        tf_buscarLlantas = new javax.swing.JTextField();
        jl_Buscar1 = new javax.swing.JLabel();
        bt_verLlanta = new javax.swing.JButton();
        bt_agregarLlanta = new javax.swing.JButton();
        bt_modificarLlanta = new javax.swing.JButton();
        bt_eliminarLlanta = new javax.swing.JButton();
        jcb_filtroBusquedaLlanta = new javax.swing.JComboBox();
        jp_aros = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_aros = new javax.swing.JTable();
        tf_buscarAro = new javax.swing.JTextField();
        jl_Buscar2 = new javax.swing.JLabel();
        bt_verAro = new javax.swing.JButton();
        bt_agregarAro = new javax.swing.JButton();
        bt_modificarAro = new javax.swing.JButton();
        bt_eliminarAro = new javax.swing.JButton();
        jcb_filtroBusquedaAro = new javax.swing.JComboBox();
        jp_facturacion = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_telefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_cedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_direccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rb_cliente_nuevo = new javax.swing.JRadioButton();
        cb_nombre_cliente = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_linea_factura = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        sp_cantidad = new javax.swing.JSpinner();
        bt_agregar_linea = new javax.swing.JButton();
        tf_precio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rb_producto_nuevo = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cb_producto = new javax.swing.JComboBox<>();
        bt_imprimir = new javax.swing.JButton();
        rb_contado = new javax.swing.JRadioButton();
        rb_credito = new javax.swing.JRadioButton();

        jmi_ver.setText("Ver");
        jmi_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_verActionPerformed(evt);
            }
        });
        pum_tb.add(jmi_ver);

        jmi_modificar.setText("Modificar");
        jmi_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_modificarActionPerformed(evt);
            }
        });
        pum_tb.add(jmi_modificar);

        jmi_eliminar.setText("Eliminar");
        jmi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarActionPerformed(evt);
            }
        });
        pum_tb.add(jmi_eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LLantas y Reencauches Griegos");

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        panel_tabs.setMaximumSize(new java.awt.Dimension(1080, 720));
        panel_tabs.setMinimumSize(new java.awt.Dimension(1080, 720));
        panel_tabs.setPreferredSize(new java.awt.Dimension(1080, 720));

        jp_clientes.setBackground(new java.awt.Color(51, 51, 51));
        jp_clientes.setForeground(new java.awt.Color(102, 102, 102));
        jp_clientes.setMaximumSize(new java.awt.Dimension(1080, 720));
        jp_clientes.setMinimumSize(new java.awt.Dimension(1080, 720));
        jp_clientes.setName(""); // NOI18N
        jp_clientes.setPreferredSize(new java.awt.Dimension(1080, 720));
        jp_clientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_Buscar.setBackground(new java.awt.Color(153, 153, 153));
        jl_Buscar.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jl_Buscar.setForeground(new java.awt.Color(204, 204, 204));
        jl_Buscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Buscar.setText("Buscar");
        jl_Buscar.setPreferredSize(new java.awt.Dimension(102, 33));
        jp_clientes.add(jl_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 19, 102, 33));

        tf_buscarCliente.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tf_buscarCliente.setForeground(new java.awt.Color(51, 51, 51));
        tf_buscarCliente.setPreferredSize(new java.awt.Dimension(946, 34));
        tf_buscarCliente.setSelectionColor(new java.awt.Color(153, 153, 153));
        tf_buscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_buscarClienteKeyReleased(evt);
            }
        });
        jp_clientes.add(tf_buscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 20, 946, 34));

        bt_ver.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        bt_ver.setText("Ver");
        bt_ver.setPreferredSize(new java.awt.Dimension(102, 33));
        bt_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_verActionPerformed(evt);
            }
        });
        jp_clientes.add(bt_ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 72, 102, 33));

        bt_agregar.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        bt_agregar.setText("Agregar");
        bt_agregar.setPreferredSize(new java.awt.Dimension(102, 33));
        bt_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregarActionPerformed(evt);
            }
        });
        jp_clientes.add(bt_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 122, -1, -1));

        bt_modificar.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        bt_modificar.setText("Modificar");
        bt_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificarActionPerformed(evt);
            }
        });
        jp_clientes.add(bt_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 172, -1, -1));

        bt_eliminar.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        bt_eliminar.setText("Eliminar");
        bt_eliminar.setPreferredSize(new java.awt.Dimension(102, 33));
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });
        jp_clientes.add(bt_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 222, -1, -1));

        jt_clientes.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jt_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Cedula", "Telefono"
            }
        ));
        jt_clientes.setComponentPopupMenu(pum_tb);
        jt_clientes.setGridColor(new java.awt.Color(51, 51, 51));
        jt_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jt_clientesMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jt_clientes);

        jp_clientes.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 72, 946, 640));

        panel_tabs.addTab("Clientes", jp_clientes);

        jp_llantas.setBackground(new java.awt.Color(51, 51, 51));
        jp_llantas.setMaximumSize(new java.awt.Dimension(1080, 720));
        jp_llantas.setMinimumSize(new java.awt.Dimension(1080, 720));
        jp_llantas.setPreferredSize(new java.awt.Dimension(1080, 720));
        jp_llantas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setFont(new java.awt.Font("FreeSans", 1, 14)); // NOI18N

        jt_llantas.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jt_llantas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt_llantas.setComponentPopupMenu(pum_tb);
        jt_llantas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jt_llantasMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jt_llantas);

        jp_llantas.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 72, 946, 640));

        tf_buscarLlantas.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tf_buscarLlantas.setPreferredSize(new java.awt.Dimension(813, 34));
        tf_buscarLlantas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_buscarLlantasKeyReleased(evt);
            }
        });
        jp_llantas.add(tf_buscarLlantas, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 20, 813, 34));

        jl_Buscar1.setBackground(new java.awt.Color(153, 153, 153));
        jl_Buscar1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jl_Buscar1.setForeground(new java.awt.Color(204, 204, 204));
        jl_Buscar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Buscar1.setText("Buscar");
        jl_Buscar1.setPreferredSize(new java.awt.Dimension(102, 33));
        jp_llantas.add(jl_Buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 19, 102, 33));

        bt_verLlanta.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        bt_verLlanta.setText("Ver");
        bt_verLlanta.setPreferredSize(new java.awt.Dimension(102, 33));
        bt_verLlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_verLlantaActionPerformed(evt);
            }
        });
        jp_llantas.add(bt_verLlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 72, -1, -1));

        bt_agregarLlanta.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        bt_agregarLlanta.setText("Agregar");
        bt_agregarLlanta.setMaximumSize(new java.awt.Dimension(52, 34));
        bt_agregarLlanta.setMinimumSize(new java.awt.Dimension(52, 34));
        bt_agregarLlanta.setPreferredSize(new java.awt.Dimension(102, 33));
        bt_agregarLlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregarLlantaActionPerformed(evt);
            }
        });
        jp_llantas.add(bt_agregarLlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 122, -1, -1));

        bt_modificarLlanta.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        bt_modificarLlanta.setText("Modificar");
        bt_modificarLlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificarLlantaActionPerformed(evt);
            }
        });
        jp_llantas.add(bt_modificarLlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 172, -1, -1));

        bt_eliminarLlanta.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        bt_eliminarLlanta.setText("Eliminar");
        bt_eliminarLlanta.setPreferredSize(new java.awt.Dimension(102, 33));
        bt_eliminarLlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarLlantaActionPerformed(evt);
            }
        });
        jp_llantas.add(bt_eliminarLlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 222, -1, -1));

        jcb_filtroBusquedaLlanta.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jcb_filtroBusquedaLlanta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Número", "Marca" }));
        jcb_filtroBusquedaLlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_filtroBusquedaLlantaActionPerformed(evt);
            }
        });
        jp_llantas.add(jcb_filtroBusquedaLlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(951, 19, 121, 35));

        panel_tabs.addTab("LLantas", jp_llantas);

        jp_aros.setBackground(new java.awt.Color(51, 51, 51));
        jp_aros.setMaximumSize(new java.awt.Dimension(1080, 720));
        jp_aros.setMinimumSize(new java.awt.Dimension(1080, 720));
        jp_aros.setPreferredSize(new java.awt.Dimension(1080, 720));
        jp_aros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setFont(new java.awt.Font("FreeSans", 1, 14)); // NOI18N

        jt_aros.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jt_aros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt_aros.setComponentPopupMenu(pum_tb);
        jt_aros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jt_arosMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jt_aros);

        jp_aros.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 72, 946, 640));

        tf_buscarAro.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tf_buscarAro.setPreferredSize(new java.awt.Dimension(813, 34));
        tf_buscarAro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_buscarAroKeyReleased(evt);
            }
        });
        jp_aros.add(tf_buscarAro, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 20, -1, -1));

        jl_Buscar2.setBackground(new java.awt.Color(153, 153, 153));
        jl_Buscar2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jl_Buscar2.setForeground(new java.awt.Color(204, 204, 204));
        jl_Buscar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Buscar2.setText("Buscar");
        jp_aros.add(jl_Buscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 19, 102, 34));

        bt_verAro.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        bt_verAro.setText("Ver");
        bt_verAro.setPreferredSize(new java.awt.Dimension(102, 33));
        bt_verAro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_verAroActionPerformed(evt);
            }
        });
        jp_aros.add(bt_verAro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 72, -1, -1));

        bt_agregarAro.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        bt_agregarAro.setText("Agregar");
        bt_agregarAro.setMaximumSize(new java.awt.Dimension(52, 34));
        bt_agregarAro.setMinimumSize(new java.awt.Dimension(52, 34));
        bt_agregarAro.setPreferredSize(new java.awt.Dimension(102, 33));
        bt_agregarAro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregarAroActionPerformed(evt);
            }
        });
        jp_aros.add(bt_agregarAro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 122, -1, -1));

        bt_modificarAro.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        bt_modificarAro.setText("Modificar");
        bt_modificarAro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificarAroActionPerformed(evt);
            }
        });
        jp_aros.add(bt_modificarAro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 172, -1, -1));

        bt_eliminarAro.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        bt_eliminarAro.setText("Eliminar");
        bt_eliminarAro.setPreferredSize(new java.awt.Dimension(102, 33));
        bt_eliminarAro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarAroActionPerformed(evt);
            }
        });
        jp_aros.add(bt_eliminarAro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 222, -1, -1));

        jcb_filtroBusquedaAro.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jcb_filtroBusquedaAro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Número", "Marca", "Código" }));
        jcb_filtroBusquedaAro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_filtroBusquedaAroActionPerformed(evt);
            }
        });
        jp_aros.add(jcb_filtroBusquedaAro, new org.netbeans.lib.awtextra.AbsoluteConstraints(951, 19, 121, 35));

        panel_tabs.addTab("Aros", jp_aros);

        jp_facturacion.setBackground(new java.awt.Color(51, 51, 51));
        jp_facturacion.setMaximumSize(new java.awt.Dimension(1080, 720));
        jp_facturacion.setMinimumSize(new java.awt.Dimension(1080, 720));
        jp_facturacion.setPreferredSize(new java.awt.Dimension(1080, 720));
        jp_facturacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Cedula");
        jLabel1.setPreferredSize(new java.awt.Dimension(75, 32));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 45, -1, -1));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Nombre");
        jLabel2.setPreferredSize(new java.awt.Dimension(75, 32));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 45, -1, -1));

        tf_telefono.setPreferredSize(new java.awt.Dimension(220, 32));
        jPanel2.add(tf_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 45, -1, -1));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Telefono");
        jLabel3.setPreferredSize(new java.awt.Dimension(75, 32));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 45, -1, -1));

        tf_cedula.setPreferredSize(new java.awt.Dimension(220, 32));
        jPanel2.add(tf_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 45, -1, -1));

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Direccion");
        jLabel4.setPreferredSize(new java.awt.Dimension(75, 32));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        tf_direccion.setPreferredSize(new java.awt.Dimension(220, 32));
        jPanel2.add(tf_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Cliente");
        jLabel6.setPreferredSize(new java.awt.Dimension(142, 32));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 9, -1, -1));

        rb_cliente_nuevo.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        rb_cliente_nuevo.setForeground(new java.awt.Color(204, 204, 204));
        rb_cliente_nuevo.setText("Cliente Nuevo");
        rb_cliente_nuevo.setPreferredSize(new java.awt.Dimension(160, 32));
        jPanel2.add(rb_cliente_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, -1, -1));

        cb_nombre_cliente.setPreferredSize(new java.awt.Dimension(220, 32));
        cb_nombre_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_nombre_clienteActionPerformed(evt);
            }
        });
        jPanel2.add(cb_nombre_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jp_facturacion.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, 1078, 130));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Producto");
        jLabel5.setPreferredSize(new java.awt.Dimension(75, 32));
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 45, -1, -1));

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Agregar Linea");
        jLabel7.setPreferredSize(new java.awt.Dimension(142, 32));
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 10, -1, -1));

        jt_linea_factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cantidad", "Detalle", "Precio Unitario", "Precio Linea"
            }
        ));
        jScrollPane4.setViewportView(jt_linea_factura);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1076, 350));

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Cantidad");
        jLabel8.setPreferredSize(new java.awt.Dimension(75, 32));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 45, -1, -1));

        sp_cantidad.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        sp_cantidad.setPreferredSize(new java.awt.Dimension(40, 32));
        jPanel3.add(sp_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 45, 80, -1));

        bt_agregar_linea.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        bt_agregar_linea.setText("Agregar Linea");
        bt_agregar_linea.setPreferredSize(new java.awt.Dimension(160, 32));
        jPanel3.add(bt_agregar_linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 45, -1, -1));

        tf_precio.setPreferredSize(new java.awt.Dimension(220, 32));
        jPanel3.add(tf_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 45, -1, -1));

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Precio");
        jLabel9.setPreferredSize(new java.awt.Dimension(75, 32));
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 45, -1, -1));

        rb_producto_nuevo.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        rb_producto_nuevo.setForeground(new java.awt.Color(204, 204, 204));
        rb_producto_nuevo.setText("Producto Nuevo");
        rb_producto_nuevo.setPreferredSize(new java.awt.Dimension(160, 32));
        jPanel3.add(rb_producto_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        jLabel10.setText("Total:");
        jLabel10.setPreferredSize(new java.awt.Dimension(220, 20));
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, -1, -1));

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        jLabel11.setText("Sub Total:");
        jLabel11.setPreferredSize(new java.awt.Dimension(220, 20));
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        jLabel12.setText("Imp. Ventas:");
        jLabel12.setPreferredSize(new java.awt.Dimension(220, 20));
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, -1, -1));

        cb_producto.setPreferredSize(new java.awt.Dimension(220, 32));
        jPanel3.add(cb_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 45, 220, -1));

        jp_facturacion.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 166, -1, 500));

        bt_imprimir.setText("Imprimir");
        bt_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_imprimirActionPerformed(evt);
            }
        });
        jp_facturacion.add(bt_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 680, -1, -1));

        rb_contado.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        rb_contado.setForeground(new java.awt.Color(204, 204, 204));
        rb_contado.setText("Contado");
        jp_facturacion.add(rb_contado, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 6, -1, -1));

        rb_credito.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        rb_credito.setForeground(new java.awt.Color(204, 204, 204));
        rb_credito.setText("Credito");
        jp_facturacion.add(rb_credito, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 6, -1, -1));

        panel_tabs.addTab("Facturación", jp_facturacion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_tabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_buscarClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_buscarClienteKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            //new AyudaF1().abrirAyuda();
        } else {
            filtrarClientes();
            jt_clientes.setRowSorter(trsfiltroCliente);
        }
    }//GEN-LAST:event_tf_buscarClienteKeyReleased

    private void bt_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_verActionPerformed
        verCliente();
    }//GEN-LAST:event_bt_verActionPerformed

    private void jmi_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_verActionPerformed
        menuitem_ver();
    }//GEN-LAST:event_jmi_verActionPerformed

    private void jmi_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_modificarActionPerformed
        menuitem_ver();
    }//GEN-LAST:event_jmi_modificarActionPerformed

    private void bt_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificarActionPerformed
        verCliente();
    }//GEN-LAST:event_bt_modificarActionPerformed

    private void bt_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregarActionPerformed
        UI_Cliente blc = new UI_Cliente(this, rootPaneCheckingEnabled);
        blc.setVisible(true);
        if (blc.actualizarLista) {
            cargarClientes();
        }
    }//GEN-LAST:event_bt_agregarActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        // TODO add your handling code here:
        eliminarCliente();
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void jmi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarActionPerformed
        // TODO add your handling code here:
        int tabseleccionado = panel_tabs.getSelectedIndex();
        switch(tabseleccionado){
            case 0:
                eliminarCliente();
                break;
            case 1:
                eliminarLlanta();
                break;
            case 2:
                eliminarAro();
                break;
            case 3:
                
                break;
        }
    }//GEN-LAST:event_jmi_eliminarActionPerformed

    private void bt_eliminarLlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarLlantaActionPerformed
        // TODO add your handling code here:
        eliminarLlanta();
    }//GEN-LAST:event_bt_eliminarLlantaActionPerformed

    private void bt_modificarLlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificarLlantaActionPerformed
        verLlanta();
    }//GEN-LAST:event_bt_modificarLlantaActionPerformed

    private void bt_verLlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_verLlantaActionPerformed
        // TODO add your handling code here:
        verLlanta();
    }//GEN-LAST:event_bt_verLlantaActionPerformed

    private void bt_agregarLlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregarLlantaActionPerformed
        // TODO add your handling code here:
        UI_Llanta uil = new UI_Llanta(this, rootPaneCheckingEnabled);
        uil.setVisible(true);
        if (uil.actualizarLista) {
            cargarLlantas();
        }
    }//GEN-LAST:event_bt_agregarLlantaActionPerformed

    private void tf_buscarLlantasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_buscarLlantasKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            //new AyudaF1().abrirAyuda();
        } else {
            filtrarLlantas();
            jt_llantas.setRowSorter(trsfiltroLlantas);
        }
    }//GEN-LAST:event_tf_buscarLlantasKeyReleased

    private void jcb_filtroBusquedaLlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_filtroBusquedaLlantaActionPerformed
        // TODO add your handling code here:
        filtrarLlantas();
        jt_llantas.setRowSorter(trsfiltroLlantas);
    }//GEN-LAST:event_jcb_filtroBusquedaLlantaActionPerformed

    private void jt_clientesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_clientesMouseReleased
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            verCliente();
        }
    }//GEN-LAST:event_jt_clientesMouseReleased

    private void jt_llantasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_llantasMouseReleased
        if (evt.getClickCount() == 2) {
            verLlanta();
        }
    }//GEN-LAST:event_jt_llantasMouseReleased

    private void jt_arosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_arosMouseReleased
        if (evt.getClickCount() == 2) {
            verAro();
        }
    }//GEN-LAST:event_jt_arosMouseReleased

    private void tf_buscarAroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_buscarAroKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            //new AyudaF1().abrirAyuda();
        } else {
            filtrarAros();
            jt_aros.setRowSorter(trsfiltroAros);
        }
    }//GEN-LAST:event_tf_buscarAroKeyReleased

    private void bt_verAroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_verAroActionPerformed
        verAro();
    }//GEN-LAST:event_bt_verAroActionPerformed

    private void bt_agregarAroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregarAroActionPerformed
        UI_Aro iua = new UI_Aro(this, rootPaneCheckingEnabled);
        iua.setVisible(true);
        if (iua.actualizarLista) {
            cargarAros();
        }
    }//GEN-LAST:event_bt_agregarAroActionPerformed

    private void bt_modificarAroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificarAroActionPerformed
        verAro();
    }//GEN-LAST:event_bt_modificarAroActionPerformed

    private void bt_eliminarAroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarAroActionPerformed
        eliminarAro();
    }//GEN-LAST:event_bt_eliminarAroActionPerformed

    private void jcb_filtroBusquedaAroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_filtroBusquedaAroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_filtroBusquedaAroActionPerformed

    private void bt_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_imprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_imprimirActionPerformed

    private void cb_nombre_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_nombre_clienteActionPerformed
        try{
            BL_Cliente cliente_seleccionado = (BL_Cliente) cb_nombre_cliente.getSelectedItem();
            if (cliente_seleccionado!=null) {
                cargarClienteSeleccionadoFactura(cliente_seleccionado);
            }
        }catch(ClassCastException e){
            System.err.println("caaaacaaaaa");    
        }
    }//GEN-LAST:event_cb_nombre_clienteActionPerformed

    
    public void menuitem_ver(){
        int tabseleccionado = panel_tabs.getSelectedIndex();
        switch(tabseleccionado){
            case 0:
                verCliente();
                break;
            case 1:
                verLlanta();
                break;
            case 2:
                verAro();
                break;
            case 3:
                
                break;
        }
    }

    public void filtrarClientes() {
        String hilera = tf_buscarCliente.getText();
        trsfiltroCliente.setRowFilter(RowFilter.regexFilter("(?i)"+hilera, 1));
    }
    
    public void filtrarAros() {
        String hilera = tf_buscarAro.getText();
        String filtro = jcb_filtroBusquedaAro.getSelectedItem() + "";
        int fila = 0;
        switch (filtro) {
            case "Marca":
                fila = 2;
                break;
            case "Número":
                fila = 1;
                break;
            case "Código":
                fila = 3;
                break;
        }
        trsfiltroAros.setRowFilter(RowFilter.regexFilter("(?i)"+hilera, fila));
    }

    public void filtrarLlantas() {
        String hilera = tf_buscarLlantas.getText();
        String filtro = jcb_filtroBusquedaLlanta.getSelectedItem() + "";
        int fila = 0;
        switch (filtro) {
            case "Marca":
                fila = 2;
                break;
            case "Número":
                fila = 1;
                break;
        }
        trsfiltroLlantas.setRowFilter(RowFilter.regexFilter("(?i)"+hilera, fila));
    }

    public void cargarClientes() {
        cliente = new BL_Cliente();
        cb_nombre_cliente.setEditable(true);
        cb_nombre_cliente.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                int tecla = e.getKeyCode(); 
                if((tecla>=65 && tecla<=90) || (tecla>=97 && tecla<=122) || tecla==KeyEvent.VK_BACK_SPACE){
                    resaltado = 0;
                    filtrar_cb_clientes(cb_nombre_cliente.getEditor().getItem()+"");
                }
            } 
            
        });
        
        
        listaClientes = cliente.cargarClientes();
        String[] nombreColumnas = {"numeroFila", "Nombre", "Dirección", "Teléfono(s)"};
        dtmClientes = new DefaultTableModel(null, nombreColumnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        cb_nombre_cliente.addItem("");
        if (!listaClientes.isEmpty()) {

            for (BL_Cliente cliente_temp : listaClientes) {
                dtmClientes.addRow(new Object[]{dtmClientes.getRowCount(), cliente_temp.getNombre(), cliente_temp.getDireccion_simple(), cliente_temp.getTelefonos()});
            }
        }
        jt_clientes.setModel(dtmClientes);
        jt_clientes.getColumnModel().getColumn(0).setMinWidth(0);
        jt_clientes.getColumnModel().getColumn(0).setMaxWidth(0);
        //((DefaultTableCellRenderer)jt_clientes.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        trsfiltroCliente = new TableRowSorter(jt_clientes.getModel());
    }

    public void cargarLlantas() {
        llanta = new BL_Llanta();
        listaLlantas = llanta.cargarLlantas();
        String[] nombreColumnas = {"numeroFila", "Numero Llanta", "Marca", "Diseño", "Capas", "Cantidad", "TipoLlanta"};
        dtmLlantas = new DefaultTableModel(null, nombreColumnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        if (!listaLlantas.isEmpty()) {
            for (BL_Llanta llanta_temp : listaLlantas) {
                dtmLlantas.addRow(new Object[]{dtmLlantas.getRowCount(), llanta_temp.getNumeroLlanta(), llanta_temp.getMarca(), llanta_temp.getDiseno(),
                    llanta_temp.getNumeroCapas(), llanta_temp.getCantidad(), llanta_temp.getTipoLlanta()});
            }
        }
        jt_llantas.setModel(dtmLlantas);
        jt_llantas.getColumnModel().getColumn(0).setMinWidth(0);
        jt_llantas.getColumnModel().getColumn(0).setMaxWidth(0);
        jt_llantas.getColumnModel().getColumn(6).setMinWidth(0);
        jt_llantas.getColumnModel().getColumn(6).setMaxWidth(0);
        trsfiltroLlantas = new TableRowSorter(jt_llantas.getModel());
        
    }
    
    public void cargarAros() {
        aro = new BL_Aro();
        listaAros = aro.cargarAros();
        String[] nombreColumnas = {"numeroFila", "Numero Aro", "Marca", "Codigo","Cantidad (Juegos)"};
        dtmAros = new DefaultTableModel(null, nombreColumnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        if (!listaAros.isEmpty()) {
            for (BL_Aro aro_temp : listaAros) {
                dtmAros.addRow(new Object[]{dtmAros.getRowCount(), aro_temp.getNumeroAro(), aro_temp.getMarca(), 
                    aro_temp.getCodigo(), aro_temp.getCantidad()});
            }
        }
        jt_aros.setModel(dtmAros);
        jt_aros.getColumnModel().getColumn(0).setMinWidth(0);
        jt_aros.getColumnModel().getColumn(0).setMaxWidth(0);
        trsfiltroAros = new TableRowSorter(jt_aros.getModel());
    }

    public void verCliente() {
        BL_Cliente clienteVer;
        if (validarSeleccion('c')) {
            UI_Cliente uic = new UI_Cliente(this, rootPaneCheckingEnabled);
            int fila = jt_clientes.getSelectedRow();
            int numeroFila = Integer.parseInt("" + jt_clientes.getValueAt(fila, 0));
            clienteVer = listaClientes.get(numeroFila);
            uic.cargarCliente(clienteVer);
            uic.setVisible(true);
            if (uic.actualizarLista) {
                cargarClientes();
            }
        }
    }

    public void verLlanta() {
        BL_Llanta llantaVer;
        if (validarSeleccion('l')) {
            UI_Llanta uill = new UI_Llanta(this, rootPaneCheckingEnabled);
            int fila = jt_llantas.getSelectedRow();
            int numeroFila = Integer.parseInt("" + jt_llantas.getValueAt(fila, 0));
            llantaVer = listaLlantas.get(numeroFila);
            uill.cargarLlanta(llantaVer);
            uill.setVisible(true);
            if (uill.actualizarLista) {
                cargarLlantas();
            }
        }
    }
    
    public void verAro() {
        BL_Aro aroVer;
        if (validarSeleccion('a')) {
            UI_Aro uia = new UI_Aro(this, rootPaneCheckingEnabled);
            int fila = jt_aros.getSelectedRow();
            int numeroFila = Integer.parseInt("" + jt_aros.getValueAt(fila, 0));
            aroVer = listaAros.get(numeroFila);
            uia.cargarAro(aroVer);
            uia.setVisible(true);
            if (uia.actualizarLista) {
                cargarAros();
            }
        }
    }
    
    public void cargarClienteSeleccionadoFactura(BL_Cliente cliente){
        cb_nombre_cliente.getEditor().setItem(cliente.getNombre());
        tf_cedula.setText(cliente.getCedula());
        tf_telefono.setText(cliente.getTelefonos());
        tf_direccion.setText(cliente.getDireccion_simple());
    }

    public boolean validarSeleccion(char t) {
        JTable temp = null;
        String mensaje="";
        switch(t){
            case 'c':
                temp = jt_clientes;
                mensaje = "ningun cliente";
;               break;
                
            case 'l':
                temp = jt_llantas;
                mensaje = "ninguna llanta";
                break;
                
            case 'a':
                temp = jt_aros;
                mensaje = "ningun aro";
                break;
        }
        filaSeleccionada = temp.getSelectedRow();
        if (filaSeleccionada >= 0) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado "+mensaje, "Llantas y reencauches Griegos", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
    }

    private void eliminarCliente() {
        BL_Cliente blCliente;
        if (validarSeleccion('c')) {
            UI_Cliente uic = new UI_Cliente(this, rootPaneCheckingEnabled);
            int fila = jt_clientes.getSelectedRow();
            int numeroFila = Integer.parseInt("" + jt_clientes.getValueAt(fila, 0));
            blCliente = listaClientes.get(numeroFila);
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar a " + blCliente.getNombre() + "?", "Alerta", JOptionPane.YES_NO_OPTION);
            if (confirmacion == JOptionPane.YES_OPTION) {
                if (blCliente.eliminarCliente()) {
                    JOptionPane.showMessageDialog(null, "Cliente Elimiado con exito", "Llantas y reencauches Griegos", JOptionPane.INFORMATION_MESSAGE);
                    cargarClientes();
                } else {
                    JOptionPane.showMessageDialog(null, "Fallo al eliminar el cliente", "Llantas y reencauches Griegos", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }
    

    private void eliminarLlanta() {
        BL_Llanta blLanta;
        if (validarSeleccion('l')) {
            int fila = jt_llantas.getSelectedRow();
            int numeroFila = Integer.parseInt("" + jt_llantas.getValueAt(fila, 0));
            blLanta = listaLlantas.get(numeroFila);
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar la llanta " + blLanta.getMarca() + " " + blLanta.getNumeroLlanta() + "?", "Alerta", JOptionPane.YES_NO_OPTION);
            if (confirmacion == JOptionPane.YES_OPTION) {
                if (blLanta.eliminarLlanta()) {
                    JOptionPane.showMessageDialog(null, "Llanta Elimiada con exito", "Llantas y reencauches Griegos", JOptionPane.INFORMATION_MESSAGE);
                    cargarLlantas();
                } else {
                    JOptionPane.showMessageDialog(null, "Fallo al eliminar el llanta", "Llantas y reencauches Griegos", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }
    
    private void eliminarAro() {
        BL_Aro blAro;
        if (validarSeleccion('a')){
            int fila = jt_aros.getSelectedRow();
            int numeroFila = Integer.parseInt("" + jt_aros.getValueAt(fila, 0));
            blAro = listaAros.get(numeroFila);
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar la aro " + blAro.getMarca()+ " " + blAro.getNumeroAro() +" "+ blAro.getCodigo()+ "?", "Alerta", JOptionPane.YES_NO_OPTION);
            if(confirmacion == JOptionPane.YES_OPTION){
                if(blAro.eliminarAro()){
                   JOptionPane.showMessageDialog(null, "Aro Eliminado con exito", "Llantas y reencauches Griegos", JOptionPane.INFORMATION_MESSAGE);
                    cargarAros();
                } else {
                   JOptionPane.showMessageDialog(null, "Fallo al eliminar el aro", "Llantas y reencauches Griegos", JOptionPane.INFORMATION_MESSAGE);
                 }
            }
        }
    }
    
    //cargar clientes en el campo nombre cliente de factura
    public void filtrar_cb_clientes(String texto_digitado){
        cb_nombre_cliente.removeAllItems();
        for (BL_Cliente cliente : listaClientes) {
            if(cliente.getNombre().toLowerCase().contains(texto_digitado.toLowerCase())){
                cb_nombre_cliente.addItem(cliente);
            }
        }
        if(!cb_nombre_cliente.isPopupVisible()){
            cb_nombre_cliente.showPopup();
        }
        cb_nombre_cliente.getEditor().setItem(texto_digitado);
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agregar;
    private javax.swing.JButton bt_agregarAro;
    private javax.swing.JButton bt_agregarLlanta;
    private javax.swing.JButton bt_agregar_linea;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_eliminarAro;
    private javax.swing.JButton bt_eliminarLlanta;
    private javax.swing.JButton bt_imprimir;
    private javax.swing.JButton bt_modificar;
    private javax.swing.JButton bt_modificarAro;
    private javax.swing.JButton bt_modificarLlanta;
    private javax.swing.JButton bt_ver;
    private javax.swing.JButton bt_verAro;
    private javax.swing.JButton bt_verLlanta;
    private javax.swing.JComboBox cb_nombre_cliente;
    private javax.swing.JComboBox<String> cb_producto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox jcb_filtroBusquedaAro;
    private javax.swing.JComboBox jcb_filtroBusquedaLlanta;
    private javax.swing.JLabel jl_Buscar;
    private javax.swing.JLabel jl_Buscar1;
    private javax.swing.JLabel jl_Buscar2;
    private javax.swing.JMenuItem jmi_eliminar;
    private javax.swing.JMenuItem jmi_modificar;
    private javax.swing.JMenuItem jmi_ver;
    private javax.swing.JPanel jp_aros;
    private javax.swing.JPanel jp_clientes;
    private javax.swing.JPanel jp_facturacion;
    private javax.swing.JPanel jp_llantas;
    private javax.swing.JTable jt_aros;
    private javax.swing.JTable jt_clientes;
    private javax.swing.JTable jt_linea_factura;
    private javax.swing.JTable jt_llantas;
    private javax.swing.JTabbedPane panel_tabs;
    private javax.swing.JPopupMenu pum_tb;
    private javax.swing.JRadioButton rb_cliente_nuevo;
    private javax.swing.JRadioButton rb_contado;
    private javax.swing.JRadioButton rb_credito;
    private javax.swing.JRadioButton rb_producto_nuevo;
    private javax.swing.JSpinner sp_cantidad;
    private javax.swing.JTextField tf_buscarAro;
    private javax.swing.JTextField tf_buscarCliente;
    private javax.swing.JTextField tf_buscarLlantas;
    private javax.swing.JTextField tf_cedula;
    private javax.swing.JTextField tf_direccion;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_telefono;
    // End of variables declaration//GEN-END:variables
}
